name: Go Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Set ENV variable
      env:
        ENV: production
      run: echo "ENV=production" >> $GITHUB_ENV

    - name: Build
      run: |
        GOOS=darwin GOARCH=arm64 go build -ldflags '-extldflags "-static"' -o pack-darwin-aarch64 
        GOOS=windows GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o pack-win-amd64.exe
        GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o pack-linux-amd64

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: pack
        path: |
          pack-darwin-aarch64 
          pack-win-amd64.exe
          pack-linux-amd64 

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.1.8
        files: |
          pack-darwin-aarch64 
          pack-win-amd64.exe
          pack-linux-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
